# Generated by Django 5.2.6 on 2025-10-11 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('url', models.URLField(verbose_name='接口地址')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('expected_response', models.TextField(blank=True, null=True, verbose_name='期望响应')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API测试用例',
                'verbose_name_plural': 'API测试用例',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='报告名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('skipped_cases', models.IntegerField(default=0, verbose_name='跳过用例数')),
                ('details', models.TextField(blank=True, null=True, verbose_name='详细报告')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('variables', models.TextField(blank=True, null=True, verbose_name='环境变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认环境')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
