# Generated by Django 5.2.6 on 2025-10-11 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('page', models.CharField(max_length=100, verbose_name='页面名称')),
                ('steps', models.TextField(verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='期望结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_test_cases', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试用例',
                'verbose_name_plural': 'UI测试用例',
                'ordering': ['-create_time'],
            },
        ),
    ]
